# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMoviesDb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMoviesDb
  	pod 'SnapKit', '~> 5.0.0'
    pod 'Cosmos', '~> 21.0'
    pod 'TagListView', '~> 1.0'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Nuke'
    pod 'YoutubeDirectLinkExtractor'
  target 'TheMoviesDbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMoviesDbUITests' do
    # Pods for testing
  end

end
